package com.tender.config;

import com.tender.model.Tender;
import com.tender.repository.TenderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class DataSeeder implements CommandLineRunner {

    @Autowired
    private TenderRepository tenderRepository;

    @Override
    public void run(String... args) {
        long count = tenderRepository.count();
        if (count == 144) {
            System.out.println("DataSeeder: Correct amount of data exists (" + count + " records), skipping seeding.");
            return;
        }

        System.out.println("DataSeeder: Clearing existing data and seeding 144 records...");
        tenderRepository.deleteAll();
        seedAllData();
        System.out.println("DataSeeder: Seeding complete! Total records: " + tenderRepository.count());
    }

    private void seedAllData() {
        tenderRepository.save(new Tender("Airports Authority Of India", "Airport/Aviation", "Rajiv Gandhi Bhawan, Safdarjung  Airport, New Delhi - 110003", "Rajiv Gandhi Bhawan, Safdarjung  Airport, New Delhi - 110003", "Sunil Kumar", "DGM (E-C)", "011-24657900", "gme-bihta@aai.aero", "2026/AAI/276578/1.", "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-06-01", "NOT REACHABLE", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("National Highway Authority of India", "Construction/ Maintenance", "Sector-10, Dwarka, New Delhi", "Sector-10, Dwarka, New Delhi", "Mohammad Safi", "CGM(Tech)", "011-25074100, 25074200", "mohammadsafi@nhai.org", "2026/NHAI/277344/1", "N/A", "GMC; GPA, CAR", "Yes", "AON,", "Not Interested", "2026-05-15", "Has Aon as their Risk Advisor", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Indian Highways Management Comapny Limited", "Construction/ Maintenance", "Second Floor, Asia Bhawan, Sector 9, Dwarka,  New Delhi", "Second Floor, Asia Bhawan, Sector 9, Dwarka,  New Delhi", "A R Chitranshi", "Chief Operating Officer", "011- 25074200", "tenders@ihmcl.com", "2026_NHAI_277262_1", "N/A", "GMC; GPA, CAR", "Yes", "Not Known", "Not Interested", "2026-06-08", "Already have a broker", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("RailTel Corporation of India", "Data Center", "Plate-A, 6th Flr, Office Block Tower-2,  East Kidwai Nagar, New Delhi - 110023", "Plate-A, 6th Flr, Office Block Tower-2,  East Kidwai Nagar, New Delhi - 110023", "Sanjai Kumar", "Chairman & Managing Director", "011-22900600", "cmdrailtel@railtelindia.com", null, "Closed", "GMC; GPA", "Unknown", "Not Known", "Not Interested", "2026-05-07", "Already closed their tender in March", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("National Small Industries Corporation", "MSME", "NSIC Bhawan, Okhla Nsic, New Delhi", "NSIC Bhawan, Okhla Nsic, New Delhi", "Sujay Khattri", "Insurance Head", "7292067025", "hoadmin@nsic.co.in", "NSIC/GMC-ASSET/2026-27 | GeM Bid", "Upcoming", "GMC; Property / Assets", "Yes", "Not Known", "Meeting Done", "2026-05-08", "GMC placed/ Tender for Asset will open in November. Done a physical with them they are open to onboard insurance brokers.", "Meeting Done(Onboarding in Process)"));
        tenderRepository.save(new Tender("GAIL(India) Limited", "Energy Storage", "GAIL (India) Limited, GAIL Bhawan, 16 Bhikaji  Cama Place, R.K. Puram, New Delhi", "GAIL (India) Limited, GAIL Bhawan, 16 Bhikaji  Cama Place, R.K. Puram, New Delhi", "Satya Prakash  Srivastava", "Chief Manager (Project)", "011-26172580", "slrnoida@gail.co.in", "GAIL/HQ/INS-EMP/2025-26/04", "Closed", "Property / Assets; GMC", "Yes", "Not Known", "Not Interested", "2026-06-19", "Closed their broker empanelment tender in April", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("ESE Energy Private Limited", "Ethnol", "Upper Ground Floor, A-4, Krishna Nagar, East Delhi,  Delhi.", "Upper Ground Floor, A-4, Krishna Nagar, East Delhi, Delhi.", "Anil Kumar Chaurasia", "Director", "9560118288", "eseenergy4@gmail.com", null, "To Be Tracked", "GMC; GPA", "Unknown", "Not Known", "Monitor", "2026-05-12", "Got no. of person named Mayank who handels insurance he said he will get back to me after confirmation.", "Called and texted him again but still not responded"));
        tenderRepository.save(new Tender("Noida Metro Rail Corporation", "Infrastructure", "Block-III, 3rd Floor, Ganga Shopping Complex, Sector-29, Noida 201301", "Block-III, 3rd Floor, Ganga Shopping Complex, Sector-29, Noida 201301", "Mr. CA Rajan Prakash", "DGM Finance", "120-2210603", "nmrcnoida@gmail.com", null, "N/A", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-06-04", "Placed for this year,with another broker", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Vidya Green Ventures Private Limited", "Ethnol", "Plot No.78, Ground Floor, Block- B Wazirpur Industrial  Area, Delhi - 110052", "Plot No.78, Ground Floor, Block- B Wazirpur Industrial Area, Delhi - 110052", "Dharam Pal Aggarwal", "Director", null, "vidyagreenventures@gmail.com", null, "To Be Tracked", "GMC; GPA", "Unknown", "Not Known", "Not Reachable", "2026-06-24", "NOT REACHABLE", "Tried calling again on 15, still not reachable"));
        tenderRepository.save(new Tender("Bakshi Land and Development Private Limited", "Hospitality", "OSE Commercial Block, Hotel Aloft, Asset 5B,  Aerocity, Hospitality District, IGI Airport, New Delhi", "OSE Commercial Block, Hotel Aloft, Asset 5B, Aerocity, Hospitality District, IGI Airport, New Delhi", "Amit Kumar", "Insurance Concerned Person", "011 46044604", "ose.secretarial@gmail.com", null, "To Be Tracked", "GMC; GPA", "No", "Not Known", "Monitor", "2026-05-07", "Do not involve Brokers said will give their email and phone no. asked to send the company profile and will talk to their team.", "still waiting on their email."));
        tenderRepository.save(new Tender("India Tourism Development Corporation", "Hospitality", "SCOPE COMPLEX, 6th Floor, Core 8, 7 Lodi Road, New Delhi - 110003", "SCOPE COMPLEX, 6th Floor, Core 8, 7 Lodi Road, New Delhi - 110003", "Mr. Aryan Gyanchandani", "Manager-Finance", "011-24307608", "directorfin@itdc.co.in", null, "N/A", "GMC; GPA", "Yes", "K.M. Dastur", "Not Interested", "2026-06-17", "Last year was placed with K.M. Dastur Reinsurance Brokers Pvt. Ltd", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("The Coalition for Disaster Resilient Infrastructure", "Infrastructure", "IIPA Bhawan, Indian Institute of Public Administration , Indraprastha Estate,New Delhi", "IIPA Bhawan, Indian Institute of Public Administration , Indraprastha Estate,New Delhi", "Raj Vikram Singh", "Senior Specialist- Disaster Risk Financing", "011-35059999", "info@cdri.world", null, "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Active Opportunity", "2026-05-21", "Our existing client", "Onging a tender process"));
        tenderRepository.save(new Tender("Delhi Metro Rail Corporation", "Infrastructure", "Metro Building, Fire Brigade Lane, Barakhamba Road, New Delhi, Delhi", "Metro Building, Fire Brigade Lane, Barakhamba Road, New Delhi, Delhi", "Manvendra Singh", "CE/Tender (O&M)", "011-23413960/23417912/ 23417921", "cetenderonm@dmrc.org, chitiz_1686@dmrc.or", "2026/DMRC/273992/1.", "N/A", "GMC; GPA", "Yes", "Marsh", "Not Interested", "2026-05-06", "Marsh India Insurance Brokers Private Ltd. is the existing broker", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Uttar Bharat Hydro Power Pvt. Ltd", "Hypro Power", "Saraswati kunj, Golf Crse Rd, Gurugram, Haryana", "Saraswati kunj, Golf Crse Rd, Gurugram, Haryana", "Mr. Bhupender Jain", "VP", "0124-2574500", null, null, "To Be Tracked", "Property / Assets; GMC", "No", "Not Known", "Not Reachable", "2026-05-11", "NOT REACHABLE", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("RITES-REMCL", "Railways", "PNB Building, Bhikaji Cama Place, New Delhi", "PNB Building, Bhikaji Cama Place, New Delhi", "Sh. Rakesh Gupta", "Chief Financial Officer", "9811915501", "rakeshgupta1@rites.com", null, "N/A", "GMC; GPA; Property", "Yes", "Prudent", "Not Interested", "2026-06-10", "Currently Prudent Insurance Brokers Private Limited is the appointed broker", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NAFED", "Fertilizers", "Ring Road, New Delhi", "Ring Road, New Delhi", "Saurav Sharma", "Insurance Head", "8510991777", "sharma210785@gmail.com", null, "To Be Tracked", "GMC; GPA", "No", "Not Known", "Follow-Up Pending", "2026-06-09", "current policy placed from iffco tokyo", "On Leave asked to get back in 1st week of July"));
        tenderRepository.save(new Tender("National Highway Logistics Management Limited", "Logistic Park", "D-21, Corporate Park, Sector-21, Dwarka, New  Delhi", "D-21, Corporate Park, Sector-21, Dwarka, New Delhi", "Raj Singh Chauhan", "VP Logistics", "011-25074100, Extn: 3419", "rajsingh.chauhan@nhlml.org", null, "To Be Tracked", "GMC; GPA", "Unknown", "Not Known", "Not Reachable", "2026-06-12", "NOT REACHABLE", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("Hindustan Syringes and Medical Devices Limited", "Medical Devices", "Narain Manzil, 23, Barakhamba Road, New Delhi", "Narain Manzil, 23, Barakhamba Road, New Delhi", "Sohail Nath", "Executive Director", "011-23314785", "legal@hmdhealthcare.com", null, "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-05-25", "talked, told them insurance concerned person sit in factory office called but was not reachable asked to drop a mail with the proposal", "Called again told that have already placed this years policies. Not intrested in meeting."));
        tenderRepository.save(new Tender("Oil and Natural Gas Corportation Limited", "Oil & Gas", "Deendayal Urja Bhavan, 5,  Nelson Mandela Marg, Vasant Kunj, New Delhi", "Deendayal Urja Bhavan, 5, Nelson Mandela Marg, Vasant Kunj, New Delhi", "Rajeeva Kumar", "Chief General Manager (Environment)", "011-26750998/ 9968282636", "head_env@ongc.co.in", "2026/ONGC/275917/1.", "N/A", "Property / Assets; GMC", "No", "Not Known", "Not Interested", "2026-05-11", "Does business directly with UNITED INDIA INSURANCE COMPANY.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Rail Vikas Nigam Limited", "Railways", "1st Floor, August Kranti Bhawan,  Bhikaji Cama Place, Africa Avenue, New Delhi", "1st Floor, August Kranti Bhawan,  Bhikaji Cama Place, Africa Avenue, New Delhi", "Vivek Kumar", "General Manager (Projects & CC)", "011 26738553", "vivek.kumar2@rvnl.org", null, "N/A", "GMC; GPA; Property", "No", "Not Known", "Not Interested", "2026-06-22", "Do not involve insurance brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("FIEO – Federation of Indian Export Organisations", "Trade Promotion / Government Body", "Niryat Bhawan, Rao Tula Ram Marg, Opp. Army Hospital R&R, New Delhi – 110057", "Niryat Bhawan, Rao Tula Ram Marg, Opp. Army Hospital R&R, New Delhi – 110057", "Mrs. Nirmala Tete", "Director Admin", "011-46042161", "nirmalatete@fieo.org", null, "N/A", "GMC; GPA", "Yes", "UNISON", "Not Interested", "2026-06-10", "Policy already placed have UNISON insurance Broking Services Pvt. Ltd as their current insurance broker.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("VDMInfra Projects LLP", "Real Estate", "A-22, Sector-P3, Greater Noida, Gautam Buddha Nagar", "A-22, Sector-P3, Greater Noida, Gautam Buddha Nagar", "Sanjeev Kumar", null, "8800118150", "vdminfraprojects@gmail.com", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-05-07", "Called on 9 Jun 2026, Doesn't involve insurance brokers", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Gabion Technologies India Limited", "Geotechnical", "38, 2nd floor, Mohhamadpur, Near Bhikaji  Cama Place, New Delhi", "38, 2nd floor, Mohhamadpur, Near Bhikaji Cama Place, New Delhi", "Madhusudan Sarda", "Managing Director", "011-46321074/ 9871063385", "info@gabionindia.com", null, "To Be Tracked", "GMC; GPA", "Unknown", "Not Known", "Not Reachable", "2026-06-23", "NOT REACHABLE", null));
        tenderRepository.save(new Tender("NTPC Limited", "Power / Energy", "NTPC Bhawan, SCOPE Complex, Lodhi Road, New Delhi – 110 003", "NTPC Bhawan, SCOPE Complex, Lodhi Road, New Delhi – 110 003", "Shri Anil Kumar Jadli", "Director – HR", "011-24360100", "insurance@ntpc.co.in", "NTPC/INS/BROKER-EMP/2025-26 | CPPP: 2025_NTPC_INS_1", "Closed", "Property / Assets; GMC", "Yes", "Not Known", "Not Interested", "2026-05-13", "ISSUE TENDER FOR APPOINTMENT OF INSURANCE BROKER(May)", "placed for this year not intrested in meeting"));
        tenderRepository.save(new Tender("SAIL", "Steel/Manufacturing", "Ispat Bhawan, Lodhi Road, New Delhi – 110 003", "Ispat Bhawan, Lodhi Road, New Delhi – 110 003", "Sh. Prabal Sandhu", "Sr.Manager(HR)", "011-24300333", "pers.itb.med@sail.in", null, "N/A", "GMC", "No", "Not Known", "Not Interested", "2026-05-22", "Doesn't have appointed insurance broker, issue tender for GMC Policy for retired employees in which both brokers and insurance company can participate.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Power Finance Corporation", "NBFC", "Urjanidhi, 1 Barakhamba Lane, Connaught Place, New Delhi – 110 001", "Urjanidhi, 1 Barakhamba Lane, Connaught Place, New Delhi – 110 001", "G Jawahar", "General Manager(HR& Admin)", "011-23456781", "hr@pfcindia.com", "PFCCL/LIA/TENDER/2025-26/03", "Closed", "Project / EAR", "Yes", "SPA Insurance, RMS ARC, PFCCL", "Not Interested", "2026-06-24", "Its subsidiary, PFC consulting Ltd, Conducts periodic e-tenders to appoint Lenders Insurance Advisors(LIA) on a Project by Project Basis. SPA Insurance Broking Sevices, RMS ARC Insurance Brokers Pvt. Ltd. have successfully qualified in past PFCCL tenders.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NBCC Ltd.", "Construction / Real Estate / Govt", "NBCC Bhawan, Lodhi Road, New Delhi – 110 003c", "NBCC Bhawan, Lodhi Road, New Delhi – 110 003c", "Raveesh Sethi", "General Manager(HRM)", "011-24366988", "raveesh_13@yahoo.com", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-05-07", "Do not Appoint Broker instead issue tender in which Insurance company and Broker both can participate.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("World Association of Small and Medium Enterprises", "Msme", "WASME International Secretariat, Plot no.4 Sector 16 A Film City Noida", "WASME International Secretariat, Plot no.4 Sector 16 A Film City Noida", "Sanjiv Layke", "Executive Secretary", "9911500858", "es@wasmeinfo.org", null, "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Active Opportunity", "2026-06-23", "Offers a Membership programe and once a part offer platform to expand inurance services", "Done"));
        tenderRepository.save(new Tender("SJVNL(Satluj Jal Vidyut Nigam)", "Electricity", "Shakti Sadan, Corporate Office Complex, Shannon, Shimla, Himachal Pradesh – 171006", "Office Block, Tower #1, 6th Floor, NBCC Complex, East Kidwai Nagar, New Delhi – 110023", "Mr. Sanjeev Gupta", "Manager-Finance", "011-61901919", "liaison.delhi@sjvn.nic.in", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-06-24", "Do not appoint brokers", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("SPMCIL – Security Printing & Minting Corporation of India Ltd.", "Currency / Security Printing / PSU", "3rd Floor, Tower-G, World Trade Centre, Nauroji Nagar, New Delhi – 110029", "3rd Floor, Tower-G, World Trade Centre, Nauroji Nagar, New Delhi – 110029", "Mr. Hema", "AM-F", "011-23701225/011-43582200", "info@spmcil.com", "SPMCIL/INS/BROKER-EMP/2025-26/01", "Closed", "GMC; GPA", "Yes", "SMC", "Not Interested", "2026-06-08", "Currently have SMC insurance brokers, closed the tender in Feb.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("CWC(Central Warehousing Corporation)", "Warehousing / Logistics / PSU", "4/1 Siri Institutional Area, Hauz Khas, New Delhi – 110016", "4/1 Siri Institutional Area, Hauz Khas, New Delhi – 110016", "Ms. Shabdita Singh", "AGM (G)", "9582373705", "singhshabdita@cewacor.nic.in", null, "N/A", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-07", "Already have a broker", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Indraprastha Institute Of Information Technology", "Education", "IIIT Delhi Okhla Ph-III, New Delhi", "IIIT Delhi Okhla Ph-III, New Delhi", "Mr. Mohit Kumar", "Tender Management", "Extn.-431", "nfo@iiitd.ac.in", "GEM/2026/B/7514715", "To Be Tracked", "GMC; GPA", "No", "Not Known", "Monitor", "2026-05-22", "Issue tender for various insurance requirement in which broker as well as insurance company can participate", "We met the eligibility criteria to apply for tender but failed to do as because quotes did not came."));
        tenderRepository.save(new Tender("NFL", "Fertilizers", "SCOPE Complex, Core-III,  7, Institutional Area, Lodhi Road, New Delhi-110003", "A-11, Sector-24, NOIDA-201301 (U.P.)", "Mr.S.K.Prajapati", "GM (F&A)", "9818580830", "skprajapati@nfl .co.in", "NFL/INS/BROKER/2025-26 | TenderDetail: 55590249", "Applied", "GMC; GPA", "Yes", "Not Known", "Applied", "2026-05-06", "Issue tender for appointed of insurance broker", "we have applied successfully"));
        tenderRepository.save(new Tender("BECIL", "Broadcasting", "BECIL BHAWAN , C56 A/17 Sector62 , Noida -201307 U.P.", "BECIL BHAWAN , C56 A/17 Sector62 , Noida -201307 U.P.", "Mr.Harmohan", "Insurance Personal", "120-4177850", "harmohan@becil.com", "BECIL/GMC/2026-27 | TOT: 142177657", "Open / Active", "GMC", "Yes", "Not Known", "Meeting Done", "2026-06-22", "new tender for policy of GMC closing on 17th June", "Meeting Done"));
        tenderRepository.save(new Tender("HITES(HLL INFRATECH SERVICE LIMITED)", "Infrastucture", "B-14 A, Sector 62, Noida-201 307", "B-14 A, Sector 62, Noida-201 307", "Chunnu Mukamina", "Senior HR", "120-4071500", "cmukambika@hllhites.com", "HITES/CO/HR/INSURANCE/26-27", "Open / Active", "GMC; GPA", "No", "Not Known", "Monitor", "2026-05-14", "Issue tender only for insurance company", "Contacted with reference to GPA tender, does not entertain broker of any kind"));
        tenderRepository.save(new Tender("IPA(Indian Port Association)", "Port and Marine", "Bhishma Pitamah Marg, New Delhi, Delhi 110003", "Bhishma Pitamah Marg, New Delhi, Delhi 110003", "Mr. Sudesh Tikku", "HR", "022 2436 8334", null, null, "N/A", "Marine / Hull", "No", "Not Known", "Not Interested", "2026-05-28", "Issue tender for HULL for both broker and insurance company.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("INDRAPRASTHA POWER GENERATION CO. LTD & PRAGATI POWER CORPORATION LIMITED", "Power / Energy", "Pragati Power station, Ring Road , New Delhi", "Pragati Power station, Ring Road , New Delhi", "Vineet Gupta", "General Manager(C&M)", "9599022986", "vineetgupta.ipgpp@gmail.com", "GM(C&M)/2027-27/EOI/03", "Open / Active", "All lines of business", "Yes", "Not Known", "Active Opportunity", "2026-07-14", "Issued tender for broker impanelment closing 14 july", null));
        tenderRepository.save(new Tender("National Film Development Corporation Limited", "Information and Broadcasting", "NFDC - FD Complex 24, Dr. Gopalrao Deshmukh Marg, Mumbai 400 026, Maharashtra.", "Room No.-401, 4th Floor, Soochna Bhavan, Phase 1, C.G.O Complex, Lodhi Road, New Delhi 110 003.", "Lalit Prasad Nauni", "Tender Management", "91 11243 69462/63", "lalit@nfdcindia.com", "NFDC/INS/MOTOR/2025-26 | Open Tender", "Open / Active", "GMC; GPA", "No", "Not Known", "Monitor", "2026-06-09", "Issue tender for insurance company.", "Has a open tender for motor insurance"));
        tenderRepository.save(new Tender("Indian Institute of Technology(Indian School of Mines)", "Education", "Indian Institute of Technology(Indian School of Mines),Dhanbad, Jharkhand", "IIT DELHI, Hauz Khas, New Delhi", "Ravi Kumar Chaurasia(name on tender)", "Deputy Registrar", "326-223-5608(Mr. Dhananjay Kumar)", "jrdtd@iitism.ac.in", "SW-INS-CPPP-004-26-27 | 2026_IIT_ISM_1", "Open / Active", "GMC; GPA", "No", "Not Known", "Not Reachable", "2026-05-15", "Final Bid Submission Date-30th June, for student insurance policy. open for broker and insurance company", "Tender No. SW-INS-CPPP-004-26-27, Tried calling many times but did not responded"));
        tenderRepository.save(new Tender("Central U.P Gas Limited", "Joint Venture of GAIL and BPCL", "7th Floor, UPSIDC  Complex, A-1/4 Lakhanpur, Kanpur -208024, U.P", "7th Floor, UPSIDC  Complex, A-1/4 Lakhanpur, Kanpur -208024, U.P", "Mr. Shekhar Kankrej", "Tender Management", "9511118781", "shekhar.kankrej@cugl.co.in", "CUGL/C&P/TEN2627/14", "Open / Active", "GMC; GPA", "No", "Not Known", "Monitor", "2026-06-19", "Issue tender for both broker and insurance company.", "CUGL/C&P/TEN2627/14 tender for renewal of asset policy insurance."));
        tenderRepository.save(new Tender("DSIIC(Delhi State Industrial and Infrasturcture Development Corporation Ltd)", "Infrastructure", "N-36, Bombay Life Building, Connaught Circus, New Delhi - 110001", "N-36, Bombay Life Building, Connaught Circus, New Delhi - 110001", "Sh. Narender Kumar Singh", "Director(Finance)", "23730261 Sh. Raj Kumar, PS", "fadsiidc@gmail.com", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-05-13", "Doesnot involve broker placed insurance need directly through tenders", "Not Intrested in meeting"));
        tenderRepository.save(new Tender("Central Medical Service Society", "Pharmaceuticals", "2nd Floor, Vishwa Yuvak Kendra, Teen Murti Marg, Opp. Police Station, Chanakyapuri, New Delhi-110021.", "2nd Floor, Vishwa Yuvak Kendra, Teen Murti Marg, Opp. Police Station, Chanakyapuri, New Delhi-110021.", "Anurodh Singh", "Tender Management", "011-21410905/06", "gmlogistics@cmss.gov.in", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-05-29", "they issue their tender only for insurance company.. brokers can participate if authorised from insurance company and represent them.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("GAIL India ltd.", "Petroleum and Gas", "GAIL Jubilee Tower, B-35 & 36, Sector - 1, Noida-201301 (Uttar Pradesh)", "GAIL Bhawan, 16 Bhikaiji Cama Place, R K Puram, New Delhi - 110066", "Mr. Alankar Sahu,", "Sr. Officer (C&P)", "05683-230329", "alankar.sahu@gail.co.in", "GAIL/NOIDA/INS/2026-27/01 | Closes Jul 1", "Open / Active", "Property / Assets; GMC", "No", "Not Known", "Monitor", "2026-06-22", "have an active tender which closes on July 1,  eligible for broker and insurance company Pre-bid meeting 13 Jun 2026", "Pre bid meeting on 13 June/ attended made clear that only insurance company"));
        tenderRepository.save(new Tender("Software Tech Parks of India", "IT/Tech", "1st Floor, Plate B, Office Block-1, East Kidwai Nagar, New Delhi - 110023", "1st Floor, Plate B, Office Block-1, East Kidwai Nagar, New Delhi - 110023", "Sandeep Nair", "Tender Management", "11-24628081", "con8.stpis.mp@gembuyer.in", null, "N/A", "GMC; GPA", "No", "Not Known", "Not Interested", "2026-05-19", "neither involver broker nor allow them to participate in tenders.", "Not Intrested in meeting"));
        tenderRepository.save(new Tender("BHEL(Bharat Heavy Electronics Limited)", "Electronics", "Corporate Office, BHEL House, Siri Fort, New Delhi - 110049, India,", "Industry Sector, Integrated Office Complex, Lodhi Road, New Delhi - 110003,", "Mr. Neeraj Kumar", "Sr. DGM", "1166 33 7598", "https://webmail.bhel.in", null, "To Be Tracked", "Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-05-12", "they occasionaly involve broker according to their need genrally issue tender for impanelment of insurance that take care of their insurance of various plants.", "tried calling not intrested in meeting"));
        tenderRepository.save(new Tender("Delhi State Civil Supplies Corporation LTD", "Supplies", "AAPURTI BHAWN; 7-9, ARAM BAGH; NEW DELHI – 110055", "AAPURTI BHAWN; 7-9, ARAM BAGH; NEW DELHI – 110055", "Shri Jai Prakash", "GM (F&A)", "011 2361 0120", "dscsc@delhi.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-24", "They take care of the insurance requirement only through government owned insurance company.", "Not Intrested in meeting"));
        tenderRepository.save(new Tender("Department of Law,(Lawyers Association of India)", "Legal", "Karkaddoma Court, New Delhi", "Karkaddoma Court, New Delhi", "DD Pandey", "Secretary", "9810389119", "ddpandey119@gmail.com", null, "N/A", "GMC", "Yes", "Not Known", "Meeting Done", "2026-06-23", "Tender inviting GMC for advocates, do not have specific classification for brokers or company if technical criteria is qualified then eligible. [Tender Intel: Source: Field meeting done; GMC tender for advocates]", "Meeting Done"));
        tenderRepository.save(new Tender("HUDCO – Housing & Urban Development Corporation", "Housing", "HUDCO Bhawan, India Habitat Centre, Lodhi Road, New Delhi – 110003", "HUDCO Bhawan, India Habitat Centre, Lodhi Road, New Delhi – 110003", "Mr.Satpal", "Tender Management", "011-24648420", "ssatpal@hudco.org", null, "Open / Active", "GMC; GPA,cyber", "Yes", "Not Known", "Meeting scheduled", "2026-06-18", "Do not directly involve insurance brokers issue tenders for both, closed tender in april.", "Scheduled meeting for monday"));
        tenderRepository.save(new Tender("Prasar Bharti", "Broadcasting", "Prasar Bharati House, Copernicus Marg, New Delhi – 110001", "Prasar Bharati House, Copernicus Marg, New Delhi – 110001", "Ms. Kanika Makhija", "Welfare section officer", "011-23421041", "groupinsurance.pb@gmail.com", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-04", "Involves only insurance company for their requirement.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NHPC(National Hydroelectric Power Corporation)", "Hydroelectricity", "NHPC Office Complex, Sector-33, Faridabad - 121003", "NHPC Office Complex, Sector-33, Faridabad - 121003", "Navin Kumar Singh", "GM(Civil) Division", "1292254677", "contcivil2-co@nhpc.nic.in", null, "N/A", "Property / Assets; GMC", "No", "No broker involvement", "Not Interested", "2026-05-12", "Only involve insurance company, and tender is also issue only for insurance company.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("CDC(Center for Disease Control)", "Medicine", "Shamnath Marg, Civil Lines, Delhi 110054", "Shamnath Marg, Civil Lines, Delhi 110054", "Mr. Ruchika Khanna", "Head Support Services", "011 2391 3148", "nsrinivasan@cdcgroup.com", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-22", "Doesnot involve broker in any sense.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("RFCL(Ramagundam Fertilizers and Chemical Limited)", "Fertilizers", "Scope Complex, Core-III 7, Institutional Area, Lodhi Road, New Delhi, South Delhi, 110003, India", "Scope Complex, Core-III 7, Institutional Area, Lodhi Road, New Delhi, South Delhi, 110003, India", "Mr. Sanjay Grover", "Manager-Finance", "120-2553600", "admin@rfcl.co.in", "RFCL/INS/BROKER-EMP/2025-26/01", "Closed", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-08", "Issue tender for broker empanelment have closed the process", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("EGIS India Ltd.", "Engineering", "Egis Tower, Plot No 80, Sector - 32 Gurgaon - 122 001", "T-305, TF, Tirupati Plaza, Sector-XI, (MLU) PKT-4, Plot No. 11, Dwarka, New Delhi, Delhi 110075", "Mr. Ashok Sharma", "Consultant", "0124 478 7800", "Vivek.A@egis-india.com", null, "To Be Tracked", "GMC; GPA", "Unknown", "Not Known", "Not Reachable", "2026-06-23", "NOT REACHABLE", "Tried contacting many times"));
        tenderRepository.save(new Tender("BSES Rajdhani Power Ltd.", "Electricity", "BSES Bhawan, Nehru Place, New Delhi", "BSES Bhawan, Nehru Place, New Delhi", "Ms. Shilpa Suman", "General Manager(C&M)", "8800919123", "shipa.suman@reliancegroupindia.com", null, "N/A", "GMC; GPA", "Yes", "Marsh", "Not Interested", "2026-05-07", "Have Marsh Insurance Broker as their advisory", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("EZOPS Technologies India Pvt. Ltd", "IT/Tech", "463 7th Ave #1504, New York, NY", "Discovery Tower, Sec 62, Noida", "Abhilasha Sinha", "HR", null, "abhilasha.sinha@ezops.co.in", null, "To Be Tracked", "GMC", "Yes", "Lockton", "Meeting Done", "2026-05-21", "Current GMC Placed by LOCKTON Insurance Brokers", "Meeting Done"));
        tenderRepository.save(new Tender("Container Corporation of India", "Logistics & Shipping", "CONCOR Bhawan, C-3, Mathura Road, Opposite Apollo Hospital, New Delhi-110076", "CONCOR Bhawan, C-3, Mathura Road, Opposite Apollo Hospital, New Delhi-110076", "PK Agrawal", "Director(Domestic Division)", "011-41673010", "concor_biz@concorindia.com", "CONCOR/INS/BROKER-EMP/2025-26/01", "Closed", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-06-16", "Closed Broker Imapnelment tender in Feburary.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Power Grid Corporation of India", "Power Transmission", "B-9, Qutub Institutional Area, Katwaria Sarai, New Delhi", "Saudamini Plot No.-2, Sector-29,Gurgaon, Haryana", "Anoop Kumar", "Chief Manager(BD)", "0124-2571700", "powergrid_ncr@powergrid.in", null, "N/A", "Property / Assets", "Yes", "Not Known", "Not Interested", "2026-06-19", "Appoint broker for All Risk Insurance for transmission of assets, did on july 2025", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("HPCL, Hindustan Petroleum Corporation Limited", "Oil & Gas", "Petroleum House,17, Jamshedji Tata Road, Mumbai", "HPCL Regional Office, 8, Shoorji Vallabhdas Margn Nehru Place, New Delhi", "Alok Kumar", "General Manager", "011-26444000", "hpcl_ncr@hpcl.in", null, "N/A", "Property / Assets; GMC", "Yes", "Hindustan Insurance", "Not Interested", "2026-06-10", "Closed in April, works with Hindustan Insurance Brokers Limited as an insurance broker, amd utilizes Finhaat Insurance Broking Pvt. Ltd for managing specific employee benefit programs", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("BPCL,Bharat Petroleum Corporation Limited", "Oil & Gas", "Bharat Bhavan,4&6 Currimbhoy Road, Ballard Estate, Mumbai", "BPCL Office, Plot No. A-5&6, Sector-1, Noida, UP", "S.S Sundararajan", "Chief Mnager(Marketing)", "0120-2474000", "bpcl_delhi@bharatpetroleum.in", null, "N/A", "Property / Assets; GMC", "No", "No broker involvement", "Not Interested", "2026-06-01", "Do not particularly engage brokers, issue policies through ICICI Lombard.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("CIL,Coal India Limited", "Mining & Coal", "Coal Bhawan, Premise No-04 MAR, Plot No-AF-III, Action Area-1A, New Town,Rajahat, Kolkata", "Core 6, 6th Floor, SCOPE Minar, Laxmi Nagar District Centre, Delhi", "Manoj Kumar", "General Manager(Sales)", "011-22448860", "gmsales.cil@coalindia.in", null, "N/A", "Property / Assets; GMC", "No", "No broker involvement", "Not Interested", "2026-06-12", "Float Tenders only for Gov. Insurance Comapny.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("DFCCIL, Dedicated Freight Corridor Corporation", "Railway Infrastructure", "5th Foor, Supreme Court Metro Station Building Complex,New Delhi", "5th Foor, Supreme Court Metro Station Building Complex,New Delhi", "Hari Mohan Gupta", "Managing Director", "011-23454700", "MD@DFCCIL.CO.In", "DFCCIL/INS/BROKER-EMP/2025-26/01", "To Be Tracked", "GMC; GPA; Property", "No", "No broker involvement", "Not Interested", "2026-06-24", "Issue tender in which both broker and insurance company participate.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Engineers India Limited", "Engineering Consultancy", "Engineers India Bhavan, 1, Bhikaji Cama Place, New Delhi", "Engineers India Bhavan, 1, Bhikaji Cama Place, New Delhi", "Vartika Shukla", "Chairman & Managing Director", "022-26762121", "cmd@eil.co.in", "EIL/INS/BROKER/2025-26/01", "Closed", "GMC; GPA", "Yes", "AON, Aon", "Not Interested", "2026-06-12", "Closed tender in Feburary, AON Insurance Broker appointed.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NBCC(India) Limited", "Construction/Real Estate", "NBCC Bhawan, Lodhi Road, New Delhi", "NBCC Bhawan, Lodhi Road, New Delhi", "K.P Mahdevaswamy", "Chairman & Managing Director", "011-24367314", "bdd@nbccinida.com", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-04", "Conduct its policies directly with public sector insurance company.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Mahanagar Telephone Nigam Limited", "Telecom", "Mahanagr Doorsanchar Sadan, 5th Floor, 9 CGO Complex, Lodhi Road, New Delhi", "Mahanagr Doorsanchar Sadan, 5th Floor, 9 CGO Complex, Lodhi Road, New Delhi", "Ravi A. Robert Jerad", "Chairman & Managing Director", "011-24319020", "cmd@bol.net.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-29", "Issue policy through tender only applicable to public sector insurance company", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("IRCON Internatinal Limited", "Construction/Railway", "C-4, District Center, Saket, New Delhi", "C-4, District Center, Saket, New Delhi", "Brijesk Kumar Gupta", "General Manager(HRM)", "011-29565666", "info@ircon.org", null, "N/A", "GMC; GPA; Property", "Yes", "Global Insurance", "Not Interested", "2026-05-25", "currently have global insurance private limited", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("FCI, Food Corporation of India", "Logistics/Food Supply", "16-20, Barakhamba Lane, New Delhi – 110001", "16-20, Barakhamba Lane, New Delhi – 110001", "A. K. Singh", "General Manager (Finance)", "011-23412228", "gm.finance@fci.gov.in", "FCI/INS/BROKER-EMP/2026-27/01", "Open / Active", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-19", "Issue tender for appointment of insurance broker, tender closes in August. Not eligible in active tender.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Hindustan Insecticides limited", "Chemicals/Fertilizers", "SCOPE Complex, Core - 6, 2nd Floor, 7 Lodi Road, New Delhi-110003", "SCOPE Complex, Core - 6, 2nd Floor, 7 Lodi Road, New Delhi-110003", null, "DGM(Commercial)", null, "commercialho@hil.gov.in", "AC/89/INSURANCE/INT", "Open / Active", "General", "Yes", "Not Known", null, "2026-06-19", "Has an open tender for broker impanelment", "no. on tender document invalid, sent an email asking for contact info"));
        tenderRepository.save(new Tender("NITI Aayog", "Government / Policy", "Sansad Marg, New Delhi – 110001", "Sansad Marg, New Delhi – 110001", "Rajiv Mehta", "Director (Administration)", "011-23096584", "admn@niti.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-25", "Does not appoint brokers, uses government insurance companies directly.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("ONGC Videsh Limited", "Oil & Gas", "Deendayal Urja Bhavan, 5, Nelson Mandela Marg, Vasant Kunj, New Delhi", "Deendayal Urja Bhavan, 5, Nelson Mandela Marg, Vasant Kunj, New Delhi", "Sanjay Vij", "General Manager (Finance)", "011-23318101", "contactovl@ongcvidesh.com", "OVL/INS/PROJECT/2026-27/Q3", "Upcoming", "Project / EAR", "Yes", "Not Known", "Not Interested", "2026-05-11", "Occasionally appoints brokers for overseas project insurance. Tender expected in Q3.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("IREDA – Indian Renewable Energy Development Agency", "Renewable Energy / Finance", "August Kranti Bhawan, Bhikaji Cama Place, New Delhi – 110066", "August Kranti Bhawan, Bhikaji Cama Place, New Delhi – 110066", "Pradip Kumar Das", "CMD", "011-26717400", "info@ireda.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-23", "Does not involve brokers for insurance requirement, directly places with PSU insurers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("National Mineral Development Corporation (NMDC)", "Mining & Minerals", "Khanij Bhawan, 10-3-311/A, Castle Hills, Masab Tank, Hyderabad", "SCOPE Minar, Core-2, Laxmi Nagar District Centre, New Delhi – 110092", "Amitava Mukherjee", "Director (Finance)", "011-22481559", "dirfinance@nmdc.co.in", "NMDC/INS/BROKER-EMP/2025-26/01", "Closed", "Property / Assets; GMC", "No", "Not Known", "Not Interested", "2026-05-29", "Issue tender for various insurance requirement in which broker as well as insurance company can participate", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Rashtriya Ispat Nigam Limited (RINL)", "Steel / Manufacturing", "Administrative Building, Visakhapatnam Steel Plant, Visakhapatnam – 530031", "SCOPE Complex, Core-6, Lodhi Road, New Delhi – 110003", "Atul Bhatt", "CMD", "011-24364500", "cmd@vizagsteel.com", "RINL/INS/BROKER-EMP/2026-27/01", "Closed", "Property / Assets", "No", "Not Known", "Not Reachable", "2026-06-18", "Closed tender for asset insurance in jan, are not involving insurance broker from last 4 years", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Airports Economic Regulatory Authority (AERA)", "Regulatory / Aviation", "AERA Building, Administrative Complex, Safdarjung Airport, New Delhi – 110003", "AERA Building, Administrative Complex, Safdarjung Airport, New Delhi – 110003", "Sanjeev Khirwar", "Chairperson", "011-24610532", "aera@aera.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-16", "Small regulatory body, handles insurance through government channels only.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("TCIL – Telecommunications Consultants India Limited", "Telecom / Consultancy", "TCIL Bhawan, Greater Kailash – I, New Delhi – 110048", "TCIL Bhawan, Greater Kailash – I, New Delhi – 110048", "Sandeep Aggarwal", "Director (Finance)", "011-26218002", "tcil@tcil-india.com", "TCIL/INS/BROKER-EMP/2025-26/01", "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-06-02", "Has issued tender for broker empanelment. Current broker details not available. Need to follow up.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("SCI – Shipping Corporation of India", "Shipping / Maritime", "Shipping House, 245 Madame Cama Road, Nariman Point, Mumbai – 400021", "Antriksh Bhavan, 22, K.G. Marg, New Delhi – 110001", "H.K. Joshi", "CMD", "011-23356400", "headoffice@sci.co.in", "SCI/INS/HULL-GMC/2026-27/01", "Upcoming", "Marine / Hull", "Yes", "Not Known", "Not Interested", "2026-06-11", "Appoints brokers for Hull & Machinery and other marine insurance. Tender for broker empanelment expected mid-year.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NLC India Limited (formerly Neyveli Lignite Corporation)", "Power / Mining", "Block-1, Neyveli – 607801, Cuddalore District, Tamil Nadu", "SCOPE Complex, Core-3, Lodhi Road, New Delhi – 110003", "Rakesh Kumar", "Director (Finance)", "011-24360190", "finance@nlcindia.in", "NLCIL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Not Reachable", "2026-05-28", "Tender for insurance broker empanelment. Current broker not confirmed. Need to track tender portal.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("MSTC Limited", "E-Commerce / PSU", "225C, A.J.C. Bose Road, Kolkata – 700020", "SCOPE Complex, Core-5, 7, Institutional Area, Lodhi Road, New Delhi – 110003", "Subrata Sarkar", "CMD", "011-24364620", "ho@mstcindia.co.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-25", "Doesn't appoint insurance brokers separately. Uses government insurance companies.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("CIPET – Central Institute of Petrochemicals Engineering & Technology", "Education / Research", "T.V.K. Industrial Estate, Guindy, Chennai – 600032", "B-32, Sector-62, Institutional Area, Noida – 201309", "S. Swaminathan", "Director General", "0120-2400631", "hq@cipet.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-08", "Central Government Institute, not interested in appointing brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NIIT Technologies (Coforge Limited)", "IT / Technology", "8, Balaji Estate, Guru Ravi Das Marg, Kalkaji, New Delhi – 110019", "Plot 62, Sector 32, Gurugram, Haryana – 122001", "Sudhir Singh", "CEO & MD", "0124-6696000", "investors@coforge.com", null, "N/A", "GMC; GPA", "Yes", "Prudent", "Not Interested", "2026-05-13", "Private IT company. Currently have Prudential insurance brokers managing their employee benefit programs.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Bharat Electronics Limited (BEL)", "Defence Electronics", "Outer Ring Road, Nagavara, Bengaluru – 560045", "BEL Complex, Ghaziabad – 201010 (UP)", "Bhanu Prakash Srivastava", "Director (Finance)", "0120-2895000", "finance@bel.co.in", "BEL/INS/BROKER-EMP/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-06-17", "Empanels insurance brokers through periodic tenders. Check BEL tender portal for upcoming tenders. [Tender Intel: Source: Field intelligence; Periodic empanelment; check BEL tender portal]", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("HAL – Hindustan Aeronautics Limited", "Defence / Aerospace", "15/1, Cubbon Road, Bengaluru – 560001", "HAL Corporate Office, Sector-16, Chandigarh Road, Panchkula", "C.B. Ananthakrishnan", "Director (Finance)", "011-23070301", "finance@hal-india.co.in", "HAL/INS/BROKER-EMP/2026-27/01", "Upcoming", "Property / Assets; Aviation", "Yes", "Not Known", "Not Interested", "2026-06-09", "Appoints insurance brokers for aircraft and plant insurance. Tender expected in Q3 2026. [Tender Intel: Source: Field intelligence; Tender expected Q3 2026 for aircraft & plant insurance]", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("BDL – Bharat Dynamics Limited", "Defence / Missiles", "Kanchanbagh, Hyderabad – 500058", "Ministry of Defence, South Block, New Delhi", "Commodore Siddharth Mishra (Retd.)", "CMD", "040-24587000", "cmdbdl@bdl-india.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-18", "Procures insurance through Defence Ministry directives. Does not appoint independent brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("HECL – Heavy Engineering Corporation Limited", "Heavy Engineering", "HEC Township, Dhurwa, Ranchi – 834004, Jharkhand", "Core-4, SCOPE Complex, Lodhi Road, New Delhi – 110003", "Ravi Bhushan", "Director (Finance)", "011-24363073", "gmf@hec.co.in", "HECL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-06-02", "Issues tenders for insurance broker empanelment. Current broker not identified.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("NALCO – National Aluminium Company Limited", "Aluminium / Mining", "NALCO Bhawan, Plot No. P/1, Nayapalli, Bhubaneswar – 751013", "SCOPE Complex, Core-6, Lodhi Road, New Delhi – 110003", "Sridhar Patra", "CMD", "011-24369400", "ho@nalcoindia.com", "NALCO/INS/BROKER-EMP/2026-27/01", "Upcoming", "Property / Assets; GMC", "Yes", "NIA", "Not Interested", "2026-05-15", "Appoints brokers through tender process. Currently working with NIA (National Insurance Company). Tender upcoming. [Tender Intel: Source: Field intelligence; NIA current insurer; broker tender upcoming]", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("IOC – Indian Oil Corporation Limited", "Oil & Gas / Refining", "IndianOil Bhawan, G-9, Ali Yavar Jung Marg, Bandra (East), Mumbai – 400051", "IndianOil Bhawan, 1, Sri Aurobindo Marg, Yusuf Sarai, New Delhi – 110016", "Shrikant Madhav Vaidya", "Chairman", "011-26268068", "contactus@indianoil.in", "IOCL/INS/REINSU/2025-26 | TenderDetail: 49837665", "Closed", "Property / Assets; GMC", "Yes", "Marsh, AON", "Not Interested", "2026-06-16", "Large PSU with significant insurance portfolio. Appoints brokers through tender empanelment process. Currently have Marsh and AON. [Tender Intel: Source: TenderDetail.com; Reinsurance market exploration tender Oct 2025–Sep 2026]", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("MMTC Limited", "Trading / PSU", "Scope Complex, Core-1, 7, Institutional Area, Lodhi Road, New Delhi – 110003", "Scope Complex, Core-1, 7, Institutional Area, Lodhi Road, New Delhi – 110003", "Vipin Anand", "CMD", "011-24369191", "ho@mmtclimited.com", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-09", "Deals with PSU insurance companies directly for their coverage. Does not appoint private brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("WAPCOS Limited", "Water / Infrastructure", "76-C, Sector 18, Gurugram – 122015, Haryana", "76-C, Sector 18, Gurugram – 122015, Haryana", "R. K. Gupta", "CMD", "0124-2399000", "wapcos@wapcos.gov.in", "WAPCOS/INS/PROJECT/2026-27/01", "To Be Tracked", "Project / EAR", "Yes", "Not Known", "Not Reachable", "2026-05-06", "Involved in overseas water infrastructure projects. Appoints brokers for project insurance. Check tender portal.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("Directorate General of Civil Aviation (DGCA)", "Regulatory / Aviation", "Opposite Safdarjung Airport, New Delhi – 110003", "Opposite Safdarjung Airport, New Delhi – 110003", "Vikram Dev Dutt", "Director General", "011-24622495", "dgca@dgca.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-08", "Regulatory authority, does not procure commercial insurance through brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Central Warehousing Corporation (CWC) – Delhi", "Warehousing / PSU", "4/1, Siri Institutional Area, Hauz Khas, New Delhi – 110016", "4/1, Siri Institutional Area, Hauz Khas, New Delhi – 110016", "Lokesh Kumar Singhwa", "CMD", "011-26517001", "cwcmd@cewacor.nic.in", null, "N/A", "Marine / Hull", "Yes", "Not Known", "Not Interested", "2026-06-22", "Periodic tenders for warehouse and cargo insurance brokers. Prior entry also exists – coordinate.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("WASME(World Association Of Small and Medium Enterprices)", "MSME", "WASME Industrial Secretariat Plot no. 4 Sector 16A Film City Noida", "WASME Industrial Secretariat Plot no. 4 Sector 16A Film City Noida", "Sanjiv Layke", "Executive Secretary", "9911500858", "es@wasmeinfo.org", null, "N/A", "GMC, GTL", "Yes", "Involve through a paid membership plan", "Meeting Done", "2026-05-29", "Involves broker through a paid member ship plan then open a base of MSMEs that can be targeted", "Meeting Done"));
        tenderRepository.save(new Tender("MOIL Limited (Manganese Ore India Limited)", "Mining / Minerals", "MOIL Towers, 1-A, Katol Road, Nagpur – 440013", "Core-4, SCOPE Complex, Lodhi Road, New Delhi – 110003", "Ajit Kumar Saxena", "CMD", "011-24362770", "moilltd@moil.nic.in", null, "N/A", "Property / Assets; GMC", "No", "No broker involvement", "Not Interested", "2026-06-23", "Does not appoint independent brokers. Works directly with public sector insurance companies.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("BEML Limited (Bharat Earth Movers Limited)", "Heavy Engineering / Defence", "BEML Soudha, 23/1, 4th Main, SR Nagar, Bengaluru – 560027", "BEML Complex, Palakkad – 678007 (HQ for NCR deals through MoD)", "Shantanu Roy", "CMD", "080-22963200", "ho@beml.co.in", "BEML/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-06-01", "Appoints brokers for plant, machinery and employee benefit insurance. Tender to be tracked on GeM/CPPP portal.", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("IOCL Pipelines Division", "Oil & Gas / Pipeline", "Sector-13, R.K. Puram, New Delhi – 110022", "Sector-13, R.K. Puram, New Delhi – 110022", "Rajiv Bansal", "Director (Pipelines)", "011-26190133", "pipelinesdiv@indianoil.in", "IOCL/PL/INS/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Not Interested", "2026-06-02", "Separate division of IOC managing pipeline insurance. Check for independent tenders separate from IOC HO.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Bank of Baroda", "Banking / BFSI", "Baroda Corporate Centre, C-26, G Block, Bandra Kurla Complex, Mumbai – 400051", "16, Parliament Street, New Delhi – 110001", "Debadatta Chand", "MD & CEO", "011-23325183", "hoinsurance@bankofbaroda.com", "BOB/INS/BROKER/GMC-GPA/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-06-03", "Large PSU bank. Appoints insurance brokers for employee GMC and GPA policies through tender.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Punjab National Bank (PNB)", "Banking / BFSI", "Plot No 4, Sector 10, Dwarka, New Delhi – 110075", "Plot No 4, Sector 10, Dwarka, New Delhi – 110075", "Atul Kumar Goel", "MD & CEO", "011-28044955", "ho.insurance@pnb.co.in", "PNB/INS/BROKER/EMPBENE/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-06-25", "Invites tenders for insurance broker for employee benefits. Tender expected annually in Q4.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Indian Bank", "Banking / BFSI", "254-260, Avvai Shanmugham Salai, Royapettah, Chennai – 600014", "Indian Bank, Zonal Office, Barakhamba Road, New Delhi – 110001", "S.L. Jain", "MD & CEO", "011-23314093", "cmd@indianbank.co.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-16", "Manages insurance portfolio through internal HR and procurement. Does not actively involve brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Canara Bank", "Banking / BFSI", "112, J.C. Road, Bengaluru – 560002", "Janpath, Connaught Place, New Delhi – 110001", "K. Satyanarayana Raju", "MD & CEO", "011-23414121", "insurancedept@canarabank.com", "CBK/INS/BROKER/GMC/2026-27/01", "To Be Tracked", "GMC", "Yes", "AON", "Not Reachable", "2026-06-24", "Appoints insurance brokers for group health and life plans. Tender process through bank procurement.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("SBI General Insurance Company", "Insurance", "Natraj, M. V. Road, Western Express Highway Junction, Andheri East, Mumbai – 400069", "Statesman House, 148, Barakhamba Road, New Delhi – 110001", "P.C. Kandpal", "MD & CEO", "011-43567890", "contact@sbigeneral.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-12", "Insurance company itself – not relevant as a client, but potential co-insurance partner.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NPCIL – Nuclear Power Corporation of India", "Nuclear Energy", "Vikram Sarabhai Bhavan, Anushaktinagar, Mumbai – 400094", "Plot No. D-39, Block D, Sector-3, Anuvrat Marg, Noida – 201301", "Ashwini Kumar Gupta", "Director (Finance)", "0120-2422000", "finance@npcil.co.in", "NPCIL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets; Liability", "Yes", "Not Known", "Not Interested", "2026-05-08", "Highly regulated. Procures specialized nuclear liability and property insurance via government empanelled brokers only.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("ECGC – Export Credit Guarantee Corporation", "Financial Services / PSU", "Express Towers, 10th Floor, Nariman Point, Mumbai – 400021", "Antriksh Bhavan, 22, K.G. Marg, New Delhi – 110001", "M. Senthilnathan", "CMD", "011-23353631", "headoffice@ecgc.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-11", "Government export credit insurer itself. Does not procure commercial insurance through brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NBCC (India) Limited – Projects Division", "Construction / Real Estate", "NBCC Bhawan, Lodhi Road, New Delhi – 110003", "NBCC Bhawan, Lodhi Road, New Delhi – 110003", "Amit Monga", "General Manager (Projects)", "011-24367400", "projects@nbccindia.com", null, "N/A", "Project / EAR", "No", "No broker involvement", "Not Interested", "2026-05-27", "Projects division places insurance directly with PSU insurers. No broker involvement.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("ITI Limited (Indian Telephone Industries)", "Telecom / Electronics", "ITI Bhawan, Doorvani Nagar, Bengaluru – 560016", "ITI Ltd., Rae Bareli Road, Mankapur, Gonda – 271308", "Rajesh Rai", "CMD", "011-23710111", "iti@itiltd.in", "ITI/INS/GMC-GPA/2026-27 | GeM Bid", "Open / Active", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-06-15", "PSU under DoT. Issues tender for insurance services. Currently running tender for GMC and GPA.", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("SIDBI – Small Industries Development Bank of India", "Financial Services / Development Bank", "SIDBI Tower, 15 Ashok Marg, Lucknow – 226001", "Aggarwal Corporate Heights, 3rd Floor, Plot No. 7C, Netaji Subhash Place, Delhi – 110034", "Sivasubramanian Ramann", "CMD", "011-47095101", "ho.delhi@sidbi.in", "SIDBI/INS/BROKER-EMP/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-08", "Appoints insurance brokers for employee benefit insurance. Expected to float tender in next quarter.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("EXIM Bank – Export-Import Bank of India", "Banking / Financial Services", "Centre One, Floor 21, World Trade Centre Complex, Mumbai – 400005", "Kanchenjunga Building, 18, Barakhamba Road, New Delhi – 110001", "Harsha Bangari", "MD", "011-23325391", "eximbank@eximbankindia.in", "EXIM/INS/BROKER/GMC-GPA/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-07", "Appoints brokers for group medical and personal accident policies annually. Track for tender. [Tender Intel: Source: Field intelligence; Annual broker appointment]", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("Airport Authority of India – CSIA Mumbai", "Airport / Aviation", "Chhatrapati Shivaji International Airport, Mumbai – 400099", "Rajiv Gandhi Bhawan, Safdarjung Airport, New Delhi – 110003", "V.K. Jatav", "Regional Executive Director", "011-24656000", "red.nr@aai.aero", null, "To Be Tracked", "Property / Assets; Aviation", "Yes", "Not Known", "Not Reachable", "2026-05-29", "AAI's northern region handles property and aviation insurance. Separate tender from earlier AAI entry. Follow up with regional office.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("Central Board of Secondary Education (CBSE)", "Education / Government", "Shiksha Sadan, 17, Institutional Area, Rouse Avenue, New Delhi – 110002", "Shiksha Sadan, 17, Institutional Area, Rouse Avenue, New Delhi – 110002", "Rahul Singh", "Controller of Examinations", "011-22367301", "cbse.nic@nic.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-23", "Government education board. Procures group insurance through government channels only.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("HUDCO – HRIDC (Housing & Roads Infrastructure Dev Corp)", "Housing / Infrastructure", "India Habitat Centre, Lodhi Road, New Delhi – 110003", "India Habitat Centre, Lodhi Road, New Delhi – 110003", "Sanjeev Ranjan", "Director (Corporate Planning)", "011-24648162", "hridc@hudco.org", "HRIDC/INS/PROJECT/2026-27/01", "Upcoming", "Project / EAR", "Yes", "Not Known", "Not Reachable", "2026-06-11", "Infrastructure arm of HUDCO. Appoints brokers for project insurance. Tender expected in Q3 2026. [Tender Intel: Source: Field intelligence; Project insurance broker tender Q3 2026]", "NOT REACHABLE"));
        tenderRepository.save(new Tender("NABARD – National Bank for Agriculture and Rural Development", "Banking / Agriculture", "Plot No. C-24, 'G' Block, Bandra-Kurla Complex, Bandra (East), Mumbai – 400051", "NABARD Delhi Regional Office, Ground Floor, Eastern Court, Janpath, New Delhi – 110001", "Shaji K.V.", "Chairman", "011-23719100", "insurance.ho@nabard.org", "NABARD/INS/BROKER/EMPBENE/2026-27/01", "Upcoming", "GMC; GPA", "Yes", "Not Known", "Not Interested", "2026-05-28", "Issues annual tender for group health and personal accident insurance for employees.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("THDC India Limited (Tehri Hydro Development Corporation)", "Hydropower / Energy", "Bhagirathi Bhavan, Bhilangana Road, Tehri – 249001 (Uttarakhand)", "Pragatipuram, 33 URI, Meerut Bypass Road, Ghaziabad – 201002", "R.K. Vishnoi", "CMD", "0135-2748601", "chairman.thdcil@thdc.co.in", "THDCIL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-06-05", "Appoints broker for hydro plant insurance and employee benefits. Check CPPP portal for upcoming tenders.", "TRIED CALLING MANY TIMES"));
        tenderRepository.save(new Tender("REC Limited (Rural Electrification Corporation)", "Power / Finance", "Core-4, SCOPE Complex, Lodhi Road, New Delhi – 110003", "Core-4, SCOPE Complex, Lodhi Road, New Delhi – 110003", "Vivek Kumar Dewangan", "CMD", "011-24368853", "recdesk@recindia.nic.in", "REC/INS/BROKER-EMP/2026-27/01", "Upcoming", "GMC", "Yes", "Not Known", "Not Interested", "2026-06-03", "Appoints insurance brokers periodically. Annual GMC tender. Check procurement portal for broker empanelment status.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("ONGC Petro Additions Limited (OPaL)", "Petrochemicals", "ONGC Petro additions Limited, Dahej SEZ Ltd., Taluka – Vagra, Bharuch – 392130", "Scope Complex, Core-2, 7, Institutional Area, Lodhi Road, New Delhi – 110003", "Sudhir Kumar Garg", "Director (Finance)", "011-24369700", "finance@opalindia.in", "OPAL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-05-05", "JV between ONGC and GSPC. Appoints brokers for major plant insurance. Tender through ONGC empanelment.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("National Seeds Corporation (NSC)", "Agriculture / PSU", "Beej Bhawan, Pusa Complex, New Delhi – 110012", "Beej Bhawan, Pusa Complex, New Delhi – 110012", "Ranjit Kumar Sahu", "CMD", "011-25847432", "nsclimited@nscl.gov.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-12", "Agriculture PSU. Manages insurance through government channels. Does not involve private brokers.", "Not Intrested in Meeting"));
        tenderRepository.save(new Tender("NBIFCL – National Buildings & Infrastructure Finance Corporation", "Infrastructure / Finance", "11th Floor, Hotel Samrat, Kautilya Marg, Chanakyapuri, New Delhi – 110021", "11th Floor, Hotel Samrat, Kautilya Marg, Chanakyapuri, New Delhi – 110021", "G. Raghuma Reddy", "MD", "011-24678901", "md@nbifcl.gov.in", null, "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-06-03", "Relatively new PSU. Set up insurance program through broker. Need to enquire about empanelment.", "NOT REACHABLE"));
        tenderRepository.save(new Tender("Tata Power Delhi Distribution Limited", "Power / Energy", "Grant Plaza, Najafgarh Road, New Delhi – 110015", "Grant Plaza, Najafgarh Road, New Delhi – 110015", "Anjali Bansal", "Chief Manager (HR)", "011-66112222", "insurance@tatapower-ddl.com", "TPDDL/INS/BROKER-EMP/2026-27/01", "Upcoming", "GMC; GPA; Property / Assets", "Yes", "Not Known", "Monitor", "2026-05-18", "Discom serving North/North-West Delhi. Appoints brokers for employee benefit and asset insurance through annual tender.", "Spoke to HR desk, asked to send company profile for review."));
        tenderRepository.save(new Tender("Indraprastha Gas Limited", "City Gas Distribution", "IGL Bhawan, Plot No. 4, Community Centre, Sector 9, R.K. Puram, New Delhi – 110022", "IGL Bhawan, Plot No. 4, Community Centre, Sector 9, R.K. Puram, New Delhi – 110022", "Rakesh Mittal", "General Manager (HR & Admin)", "011-41636200", "hr@igl.co.in", "IGL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "GMC; GPA; Property / Assets", "Yes", "Not Known", "Active Opportunity", "2026-05-13", "City gas distribution PSU JV. Open to broker discussions for GMC renewal in Q3.", "Had a positive call, asked for formal proposal via email."));
        tenderRepository.save(new Tender("Delhi Jal Board", "Water / Government", "Varunalaya, Karol Bagh, New Delhi – 110005", "Varunalaya, Karol Bagh, New Delhi – 110005", "Suresh Chandra", "Chief Engineer (HR)", "011-25674488", "ceho@delhijalboard.nic.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-16", "Government water utility. Procures insurance only through empanelled PSU insurers.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Haryana Power Generation Corporation Limited (HPGCL)", "Power / Energy", "Shakti Bhawan, Sector-6, Panchkula, Haryana – 134109", "C-7, Sector-6, Panchkula (NCR liaison office, Sector-1, Gurugram)", "Vinod Yadav", "Chief Engineer (Insurance)", "0172-2590400", "ceinsurance@hpgcl.org.in", "HPGCL/INS/BROKER-EMP/2026-27/01", "Upcoming", "Property / Assets; GMC", "Yes", "Not Known", "Monitor", "2026-05-07", "State power gen company. Appoints brokers for plant insurance through periodic tenders.", "Asked to call back after their board meeting next week."));
        tenderRepository.save(new Tender("Haryana Vidyut Prasaran Nigam Limited (HVPNL)", "Power Transmission", "Shakti Bhawan, Sector-6, Panchkula, Haryana – 134109", "Vidyut Sadan, Sector-33, Gurugram, Haryana", "Manoj Kataria", "Superintending Engineer (Tech)", "0124-2322100", "setech@hvpn.org.in", "HVPNL/INS/PROJECT/2026-27/01", "To Be Tracked", "Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-05-21", "Transmission utility, appoints brokers for asset all-risk policies.", "TRIED CALLING MULTIPLE TIMES"));
        tenderRepository.save(new Tender("Dakshin Haryana Bijli Vitran Nigam (DHBVN)", "Power Distribution", "Vidyut Sadan, Vidyut Nagar, Hisar, Haryana – 125005", "Plot No. 9, Sector-14, Faridabad, Haryana", "Sanjay Dahiya", "Chief Accounts Officer", "01662-220300", "cao@dhbvn.org.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-28", "State discom. Insurance procured directly via PSU insurer empanelment.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Uttar Haryana Bijli Vitran Nigam (UHBVN)", "Power Distribution", "Vidyut Sadan, Vidyut Nagar, Panchkula, Haryana – 134109", "SCO 17-18, Sector-14, Panchkula, Haryana", "Pooja Sharma", "Sr. Accounts Officer", "0172-2570600", "saohq@uhbvn.org.in", "UHBVN/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "GMC; GPA", "Yes", "Not Known", "Not Reachable", "2026-05-14", "Discom for North Haryana. Issues broker empanelment tenders occasionally.", "NOT REACHABLE, will retry."));
        tenderRepository.save(new Tender("Housing and Urban Development Corporation - Noida Unit", "Housing / Infrastructure", "C-56/16, Sector-62, Noida – 201307", "C-56/16, Sector-62, Noida – 201307", "Deepali Saxena", "Manager (Admin)", "0120-4567800", "noida@hudco.org", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-25", "Regional unit office, insurance handled centrally by HUDCO HO.", "Redirected to head office team."));
        tenderRepository.save(new Tender("Uttar Pradesh Power Corporation Limited (UPPCL)", "Power Distribution", "Shakti Bhawan, 14, Ashok Marg, Lucknow – 226001", "Vidyut Bhawan, Sector-12, Noida – 201301", "Anand Tripathi", "Chief Engineer (Commercial)", "0120-2515500", "ce.commercial@uppcl.org", "UPPCL/INS/BROKER-EMP/2026-27/01", "Upcoming", "GMC; GPA; Property / Assets", "Yes", "Not Known", "Follow-Up Pending", "2026-06-08", "Large state discom. Tender for broker empanelment expected after monsoon review.", "Asked to follow up first week of July."));
        tenderRepository.save(new Tender("Noida Power Company Limited", "Power Distribution", "NPCL Bhawan, Sector-1, Greater Noida, U.P. – 201310", "NPCL Bhawan, Sector-1, Greater Noida, U.P. – 201310", "Ritu Agarwal", "Head – HR", "0120-2326700", "hr@noidapower.com", null, "N/A", "GMC; GPA", "Yes", "RKA", "Not Interested", "2026-06-08", "Private discom for Greater Noida. Already has RKA Insurance Brokers Pvt. Ltd. as advisor.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Greater Noida Industrial Development Authority (GNIDA)", "Infrastructure / Government", "Bhawan No. 02, Knowledge Park IV, Greater Noida, U.P. – 201310", "Bhawan No. 02, Knowledge Park IV, Greater Noida, U.P. – 201310", "Narendra Bhooshan", "Chief Executive Officer", "0120-2336046", "ceo@greaternoidaauthority.in", "GNIDA/INS/PROJECT/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Monitor", "2026-06-16", "Development authority, occasionally appoints brokers for asset and project insurance.", "Asked to send company profile by email."));
        tenderRepository.save(new Tender("Yamuna Expressway Industrial Development Authority (YEIDA)", "Infrastructure / Government", "Tower-3, 3rd Floor, Yamuna Expressway, Sector 18, Greater Noida, U.P.", "Tower-3, 3rd Floor, Yamuna Expressway, Sector 18, Greater Noida, U.P.", "Arun Vir Singh", "Chief Executive Officer", "0120-2640900", "ceo@yeida.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-11", "Development authority, handles insurance through government channels.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Ghaziabad Nagar Nigam", "Municipal / Government", "GDA Complex, Nehru Nagar, Ghaziabad, U.P. – 201001", "GDA Complex, Nehru Nagar, Ghaziabad, U.P. – 201001", "Mahendra Pratap Singh", "Municipal Commissioner", "0120-2820100", "commissioner@ghaziabadnagarnigam.in", null, "N/A", "GMC; Property / Assets", "No", "No broker involvement", "Not Interested", "2026-05-18", "Municipal body. Insurance, if any, handled through state government empanelment.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Faridabad Smart City Limited", "Infrastructure / Smart City", "Old Faridabad, Sector 12, Faridabad, Haryana – 121007", "Old Faridabad, Sector 12, Faridabad, Haryana – 121007", "Yashpal Yadav", "General Manager (Finance)", "0129-2415600", "ceo@faridabadsmartcity.org", "FSCL/INS/PROJECT/2026-27/01", "To Be Tracked", "Project / EAR; Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-06-11", "Smart City SPV. Appoints brokers for project-linked asset insurance.", "TRIED CALLING MULTIPLE TIMES"));
        tenderRepository.save(new Tender("Gurugram Metropolitan Development Authority (GMDA)", "Infrastructure / Government", "Bandhwari Road, Sector 44, Gurugram, Haryana – 122003", "Bandhwari Road, Sector 44, Gurugram, Haryana – 122003", "Ashok Garg", "DGM", "0124-4538900", "ceo@gmda.gov.in", "GMDA/INS/PROJECT/2026-27/01", "Upcoming", "Property / Assets; GMC", "Yes", "Not Known", "Monitor", "2026-06-08", "Development authority for Gurugram. Tender for project insurance expected next quarter.", "Asked us to check back after monsoon infra review."));
        tenderRepository.save(new Tender("Haryana Shahari Vikas Pradhikaran (HSVP)", "Infrastructure / Government", "HSVP Bhawan, Sector-6, Panchkula, Haryana – 134109", "C-3, Sector-14, Gurugram, Haryana", "Vikram Antil", "Estate Officer", "0124-2322500", "eo.gurugram@hsvp.org.in", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-06-22", "Urban development authority, does not engage private brokers.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Delhi International Airport Limited (DIAL)", "Airport / Aviation", "Indira Gandhi International Airport, New Delhi – 110037", "Indira Gandhi International Airport, New Delhi – 110037", "Videh Kumar Jaipuriar", "Chief Executive Officer", "011-23376000", "insurance@gmrgroup.in", "DIAL/INS/BROKER-EMP/2026-27/01", "Upcoming", "Property / Assets; Aviation; GMC", "Yes", "Marsh", "Not Interested", "2026-05-27", "GMR-led airport operator. Currently has Marsh as insurance broker for asset and liability cover.", "Not interested, broker already appointed."));
        tenderRepository.save(new Tender("Delhi Development Authority (DDA)", "Urban Development / Government", "Vikas Sadan, INA, New Delhi – 110023", "Vikas Sadan, INA, New Delhi – 110023", "Subhasish Panda", "Vice Chairman", "011-24617935", "vc@dda.org.in", null, "N/A", "GMC; GPA; Property / Assets", "No", "No broker involvement", "Not Interested", "2026-05-14", "Government urban body. Procures insurance through public sector insurers directly.", "Not interested in meeting."));
        tenderRepository.save(new Tender("New Delhi Municipal Council (NDMC)", "Municipal / Government", "Palika Kendra, Sansad Marg, New Delhi – 110001", "Palika Kendra, Sansad Marg, New Delhi – 110001", "Amit Yadav", "Chairperson", "011-23362295", "chairperson@ndmc.gov.in", "NDMC/INS/PROPERTY/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Monitor", "2026-06-10", "Municipal council. Floats periodic tenders for property and employee insurance.", "Spoke to office, asked to send profile for record."));
        tenderRepository.save(new Tender("IFFCO – Indian Farmers Fertiliser Cooperative Limited", "Fertilizers", "IFFCO Sadan, C-1, District Centre, Saket Place, New Delhi – 110017", "IFFCO Sadan, C-1, District Centre, Saket Place, New Delhi – 110017", "Udai Shanker Awasthi", "Managing Director", "011-26529023", "md@iffco.in", "IFFCO/INS/BROKER-EMP/2025-26/02", "Closed", "GMC; Property / Assets", "Yes", "Not Known", "Not Interested", "2026-06-22", "Large cooperative fertilizer producer. Closed broker empanelment tender earlier this year.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Kribhco – Krishak Bharati Cooperative Limited", "Fertilizers", "A-10, Sector-1, Noida, U.P. – 201301", "A-10, Sector-1, Noida, U.P. – 201301", "Rajneesh Kumar Garg", "Director (Finance)", "0120-2511000", "finance@kribhco.net", "KRIBHCO/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "GMC; Property / Assets", "Yes", "Not Known", "Not Reachable", "2026-05-27", "Cooperative fertilizer society headquartered in Noida. Appoints brokers periodically.", "TRIED CALLING MULTIPLE TIMES"));
        tenderRepository.save(new Tender("Indian Renewable Energy Development Agency - Project Cell", "Renewable Energy", "Core 4A, East Court, India Habitat Centre, Lodhi Road, New Delhi – 110003", "Core 4A, East Court, India Habitat Centre, Lodhi Road, New Delhi – 110003", "Manoj Kumar Dwivedi", "Chief General Manager (Projects)", "011-26537269", "projects@ireda.in", "IREDA/PROJ/INS/2026-27/01", "Upcoming", "Project / EAR", "Yes", "Not Known", "Active Opportunity", "2026-06-09", "Project finance cell separate from IREDA HO entry. Open to discussing broker tie-up for project EAR covers.", "Good response, scheduling a follow-up call next week."));
        tenderRepository.save(new Tender("Solar Energy Corporation of India (SECI)", "Renewable Energy", "1st Floor, A Wing, D-3, District Centre, Saket, New Delhi – 110017", "1st Floor, A Wing, D-3, District Centre, Saket, New Delhi – 110017", "Subrahmanyam Pulipaka", "Chief Financial Officer", "011-49495000", "cfo@seci.co.in", "SECI/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Monitor", "2026-06-03", "PSU promoting solar power projects. Tender for broker empanelment expected this year.", "Asked to send brochure, will discuss with management."));
        tenderRepository.save(new Tender("Pawan Hans Limited", "Aviation / Helicopter Services", "C-14, Qutub Institutional Area, New Delhi – 110016", "C-14, Qutub Institutional Area, New Delhi – 110016", "Praveen Kaushik", "General Manager (Finance)", "011-26963653", "finance@pawanhans.co.in", "PHL/INS/AVIATION/2026-27/01", "Upcoming", "Aviation; GMC", "Yes", "Not Known", "Not Reachable", "2026-06-05", "Helicopter services PSU. Appoints brokers for aviation hull and liability insurance.", "TRIED CALLING MULTIPLE TIMES"));
        tenderRepository.save(new Tender("Airports Authority of India - Training Academy", "Airport / Aviation / Education", "AAI Training Academy, Civil Aviation Training College, Allahabad", "Sector 21, Dwarka, New Delhi (NCR liaison)", "Rajeev Tandon", "Director (Training)", "0532-2270100", "director.cate@aai.aero", null, "N/A", "GMC; GPA", "No", "No broker involvement", "Not Interested", "2026-05-22", "Separate training wing of AAI, insurance procured centrally by AAI HO.", "Redirected to AAI head office."));
        tenderRepository.save(new Tender("Central Electronics Limited (CEL)", "Electronics / PSU", "4, Industrial Area, Sahibabad, Ghaziabad, U.P. – 201010", "4, Industrial Area, Sahibabad, Ghaziabad, U.P. – 201010", "Ashwani Kumar Sharma", "Chief General Manager", "0120-2895025", "cgm@cel.co.in", "CEL/INS/BROKER-EMP/2026-27/01", "To Be Tracked", "Property / Assets; GMC", "Yes", "Not Known", "Not Reachable", "2026-05-15", "Electronics PSU based in Ghaziabad. Likely appoints broker for plant cover.", "NOT REACHABLE, will retry next week."));
        tenderRepository.save(new Tender("Engineering Projects (India) Limited (EPI)", "Engineering / Construction", "Core-3, SCOPE Complex, 7 Institutional Area, Lodhi Road, New Delhi – 110003", "Core-3, SCOPE Complex, 7 Institutional Area, Lodhi Road, New Delhi – 110003", "Pradeep Singh Kharola", "Chairman & Managing Director", "011-24365051", "cmd@epi.gov.in", "EPI/INS/BROKER-EMP/2026-27/01", "Upcoming", "Property / Assets; Project / EAR", "Yes", "Not Known", "Monitor", "2026-05-11", "Construction PSU. Periodically appoints brokers for project EAR and asset covers.", "Asked to email proposal for internal circulation."));
        tenderRepository.save(new Tender("Cement Corporation of India Limited", "Cement / Manufacturing", "Core-7, SCOPE Complex, 7 Institutional Area, Lodhi Road, New Delhi – 110003", "Core-7, SCOPE Complex, 7 Institutional Area, Lodhi Road, New Delhi – 110003", "Rajesh Kumar Sinha", "Director (Finance)", "011-24362222", "finance@cciltd.in", null, "N/A", "Property / Assets; GMC", "No", "No broker involvement", "Not Interested", "2026-05-19", "PSU cement manufacturer. Procures insurance through government insurer channels only.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Pradhan Mantri Gram Sadak Yojana - NCR Cell (NRIDA)", "Infrastructure / Government", "NRIDA, 5th Floor, 15-NBCC Tower, Bhikaji Cama Place, New Delhi – 110066", "NRIDA, 5th Floor, 15-NBCC Tower, Bhikaji Cama Place, New Delhi – 110066", "Alok Kumar", "Director General", "011-26716930", "dg@nrida.gov.in", null, "N/A", "Property / Assets", "No", "No broker involvement", "Not Interested", "2026-05-15", "Rural roads agency. Insurance, if procured, routed through state governments.", "Not interested in meeting."));
        tenderRepository.save(new Tender("Ircon Infrastructure & Services Limited", "Construction / Railway Infrastructure", "C-4, District Centre, Saket, New Delhi – 110017", "C-4, District Centre, Saket, New Delhi – 110017", "Sanjay Kumar Chaudhary", "Managing Director", "011-29565700", "md@iisl-ircon.com", "IISL/INS/PROJECT/2026-27/01", "To Be Tracked", "Property / Assets; Project / EAR", "Yes", "Not Known", "Active Opportunity", "2026-05-22", "IRCON subsidiary handling infra leasing & services. Open to a broker introduction call.", "will release tender for broker impanelment in august"));
        tenderRepository.save(new Tender("Indian Council of Social Science Research", "Education", "JNU Institutional Area, Aruna Asaf Ali Marg, New Delhi", "JNU Institutional Area, Aruna Asaf Ali Marg, New Delhi", "Shambhu Nath Mahto", "Sectional Officer", "011-26741849/50", "cc@icssr.org", "Limited tender document on their website", "Open/Active", "Motor", "No", "No broker involvement", "Not Intrested", "2026-06-17", "Issue tender only for insurance company", null));
    }
}
